export const DASHBOARD_ROUTE: string = '/dashboard'
export const PROFILE_ROUTE: string = '/profile'
export const LOGIN_ROUTE: string = '/login'
export const REGISTER_ROUTE: string = '/register'
export const RESET_PASSWORD_ROUTE: string = '/profile/reset-password'
