export const GET_MAILING_RESET_PW_RESPONSE_TOPIC: string =
  'GET_MAILING_RESET_PW_RESPONSE_TOPIC';
export const GET_MAILING_ON_SIGNUP_RESPONSE_TOPIC: string =
  'GET_MAILING_ON_SIGNUP_RESPONSE_TOPIC';